#!/bin/bash


mysql_ready() {
        mysqladmin ping --host=test-app-mysql --user=root --password=MYSQL_ROOT_PASSWORD > /dev/null 2>&1
    }

while !(mysql_ready)
do
   sleep 5
   echo "waiting for mysql to continue..."
done

python manage.py makemigrations  --no-input
python manage.py migrate  --no-input 
python manage.py makemigrations app --no-input
python manage.py migrate app --no-input 
python manage.py collectstatic --no-input
python manage.py initadmin
#python manage.py runserver $(ip a | grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b" | grep 172.18 | head -1):8090 #test
#uwsgi --ini conf.ini
if [ $? -eq 0 ]; then
    uwsgi --ini conf.ini
else
    echo "Test Failed...exiting now"
    exit 1
fi