#!/bin/bash

python manage.py makemigrations  --no-input
python manage.py migrate  --no-input 
python manage.py makemigrations app --no-input
python manage.py migrate app --no-input 
python manage.py collectstatic --no-input
python manage.py initadmin
python manage.py test
#python manage.py runserver $(ip a | grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b" | grep 172.18 | head -1):8090
