#!/bin/bash
#echo "[STATIC SITE] YUM"
#apt-get install -y git
rm -rf wasuaje-site
echo "[STATIC SITE] git clone"
git clone https://github.com/wasuaje/wasuaje-site.git

if [ $? -ne 0 ]; then
    exit 1
fi
echo "[STATIC SITE] git clone"
cd wasuaje-site
echo "[STATIC SITE] nikola build"
nikola build
echo "[STATIC SITE] copying files"
cp -r output/* /usr/src/static-site/

###docker run --rm -i -v /root/output:/nikola dragas/nikola:alpine git clone https://github.com/wasuaje/wasuaje-site.git && cd /nikola/wasuaje-site && nikola build